### ISSUE TITLE
available game blocks

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/kindscript-microbit#10]
1 open docs

http://localhost:3232/lessons/hero/activity

2. go to ksf, click blocks

2 search for this blocks

![image](https://cloud.githubusercontent.com/assets/11206682/14093001/93dca52c-f4ff-11e5-9bcc-880f98fea35f.png)

3 this block appears missing

**Comment by pelikhan** [comment]
in KSK, sprite blocks start with the "sprite" object - then the rest. So look for <sprite> set ... to
