### ISSUE TITLE
show code - not supported 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/kindscript-microbit#11]
show code: not supported in all browsers

1 open browser (MS Edge)

2 enter this code in blocks

```
basic.showNumber(7)
```
3 click on show code

![image](https://cloud.githubusercontent.com/assets/11206682/14118321/da444760-f59d-11e5-8325-f36b3ed4d4e5.png)

4 this feature does not work in Edge

**Comment by pelikhan** [comment]
Fixed in latest.
