### ISSUE TITLE
is showAnimation a supported API? 

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/kindscript-microbit#19]
is showAnimation a supported API? 

see this example...

http://localhost:3232/lessons/rotation-animation/quiz

if not, we should think of a global find/replace for the replacement API

![image](https://cloud.githubusercontent.com/assets/11206682/14156985/f958e198-f67d-11e5-84c5-7e43f93fdfd1.png)

**Comment by pelikhan** [comment]
Not supported in blocks.
