### ISSUE TITLE
blocks not rendering - specific page

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/kindscript-microbit#25]
1 spinner activity / challenge page not rendering blocks for unknown reason

2 go to activity / challenges

http://localhost:3232/lessons/spinner/activity

http://localhost:3232/lessons/spinner/challenges

3 issue is noted below

![image](https://cloud.githubusercontent.com/assets/11206682/14158991/49c94e56-f688-11e5-9196-690b96c0035e.png)

**Comment by pelikhan** [comment]
Using `=` instead of `==`
