### ISSUE TITLE
setBrightness - still not rendering or working properly

### ISSUE THREAD

**Issue by mebrauns** [Microsoft/kindscript-microbit#26]
0 go to my docs. page not rendering the blocks

http://localhost:3232/lessons/night-light/quiz-answers

![image](https://cloud.githubusercontent.com/assets/11206682/14159519/20b96dae-f68b-11e5-8232-cd983a4ea77f.png)

1 go to KSF, JS

2 enter this code

```
led.setBrightness(128)
led.plotAll()
```

```
led.setBrightness(255)
led.plotAll()
```

there is no difference in brightness

**Comment by pelikhan** [comment]
Please make sure that all APIs are supported in blocks.
